[package]
name = "relayr"
version = "0.4.1"
edition = "2024"
description = "Cron scheduler with a delegated-flavour syntax"
license = "MIT OR Apache-2.0"

[dependencies]
async-cron-scheduler = "2.0.1"
chrono = "0.4.40"
smol = "2.0.2"
inventory = "0.3.20"
relayr-macros = { path = "../relayr-macros", version = "0.4.0" }
tokio = { version = "1", features = ["full"] }
lazy_static = "1.5.0"
anyhow = "1.0.98"

[dev-dependencies]
chrono-tz = "0.10.3"
