[package]
name = "relayr"
version = "0.2.0"
edition = "2024"
description = "Cron scheduler with a delegated-flavour syntax"
license = "MIT OR Apache-2.0"

[dependencies]
async-cron-scheduler = "2.0.1"
chrono = "0.4.40"
smol = "2.0.2"
inventory = "0.3.20"
relayr-macros = { path = "../relayr-macros", version = "0.2.0" }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
