[package]
name = "relayr-macros"
version = "0.4.0"
edition = "2024"
description = "Relayr macros for the relayr crate"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
croner = "2.1.0"
quote = "1.0.40"
syn = { version = "2.0.100", features = ["full"] }
